version: '3.8'

services:
  nuxt-app:
    build:
      context: .
      args:
        BASE_URL: ${BASE_URL}
    ports:
      - '3000:3000'
    environment:
      - BASE_URL=${BASE_URL}
      - NODE_ENV=production
    restart: unless-stopped
